#ifndef _STRINGS_H
#define _STRINGS_H

char* TITLE_PREROLL = " PIXELSIEGE.NET\n\nPROUDLY PRESENTS\0";
char* TITLE_COPYRIGHT = "MADE BY MADPEW FOR OPENJAM 2018\0";

char* STR_INTRO_1 = "SHHH! HAVE YOU\nHEARD? YOU CAN\nMAKE LOTSA MONEY\nBY SPAMMING!\nIT IS SO SIMPLE.\n- FIND TARGETS\n- SEND MAILS\n- ???\n- PROFIT!\0";
char* STR_LETSGO = "ALRIGHT,\nLET'S GO\0";

// EVENTS:
const char* STR_EVENT_1 = "NEW SPAMFILTERS\nARE BLOCKING OUR\nEMAILS.\0";
const char* STR_EVENT_2 = "SHHHHH, I GOT AN\nBRANDNEW EXPLOIT\nFOR SALE.\0";

const char* STR_EVENT_3 = "HEY, YOUR BOTNET\nIS BEEING DDOS'D\0";
const char* STR_EVENT_4 = "WANNA TRANSLATE\0";

const char* STR_OFFER_REPLY = "SURE NO";
#endif /* _STRINGS_H */