#ifndef _STRINGS_H
#define _STRINGS_H

char* TITLE_PREROLL = " PIXELSIEGE.NET\n\nPROUDLY PRESENTS\0";
char* STR_INTRO_1 = "SHHH! HAVE YOU\nHEARD? YOU CAN\nMAKE LOTSA MONEY\nBY SPAMMING!\nIT IS SO SIMPLE.\n- FIND TARGETS\n- SEND MAILS\n- ???\n- PROFIT!\0";
char* STR_LETSGO = "ALRIGHT,\nLET'S GO\0";

#endif /* _STRINGS_H */